import React from 'react';

export const styles: { [key: string]: React.CSSProperties } = {
    app: { backgroundColor: 'var(--bg-main)', minHeight: '100vh' },
    appHeader: { backgroundColor: 'var(--bg-content)', padding: '16px 40px', borderBottom: '1px solid var(--border-color)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
    appTitle: { margin: 0, fontSize: '1.75rem', fontWeight: 800, color: 'var(--primary-color)' },
    mainContent: { padding: '40px' },
    header: { fontSize: '2.25rem', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '16px'},
    pageDescription: { fontSize: '1rem', color: 'var(--text-secondary)', marginBottom: '32px', maxWidth: '800px' },
    headerActions: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' },
    card: { backgroundColor: 'var(--bg-content)', padding: '24px', borderRadius: 'var(--radius-lg)', boxShadow: 'var(--shadow-md)', marginBottom: '24px' },
    storeGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '24px' },
    storeCardTitle: { margin: 0, fontSize: '1.1rem', fontWeight: 600, color: 'var(--text-primary)' },
    storeCardAddress: { margin: '4px 0 0 0', fontSize: '0.875rem', color: 'var(--text-secondary)' },
    table: { width: '100%', borderCollapse: 'collapse' },
    th: { backgroundColor: 'var(--bg-header)', padding: '12px 16px', borderBottom: '1px solid var(--border-color)', textAlign: 'left', fontWeight: 600, fontSize: '0.875rem', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '0.05em' },
    td: { padding: '16px', borderBottom: '1px solid var(--border-color)', verticalAlign: 'middle', color: 'var(--text-primary)' },
    button: { cursor: 'pointer', padding: '10px 20px', border: 'none', borderRadius: 'var(--radius-md)', fontSize: '0.95rem', fontWeight: 600, transition: 'background-color 0.2s, box-shadow 0.2s', display: 'inline-flex', alignItems: 'center', gap: '8px' },
    buttonPrimary: { backgroundColor: 'var(--primary-color)', color: 'white' },
    buttonSecondary: { backgroundColor: 'var(--secondary-color)', color: 'white' },
    buttonDanger: { backgroundColor: 'var(--danger-color)', color: 'white' },
    buttonSuccess: { backgroundColor: 'var(--success-color)', color: 'white' },
    buttonOutline: { backgroundColor: 'transparent', color: 'var(--text-secondary)', border: '1px solid var(--border-color)'},
    buttonIcon: { padding: '10px', lineHeight: 1, gap: 0 },
    buttonIconSmall: { padding: '8px', lineHeight: 1, gap: 0 },
    input: { width: 'calc(100% - 24px)', padding: '12px', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-md)', fontSize: '1rem', transition: 'border-color 0.2s, box-shadow 0.2s', background: 'var(--bg-content)', color: 'var(--text-primary)' },
    select: { width: '100%', padding: '12px', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-md)', fontSize: '1rem', backgroundColor: 'var(--bg-content)', color: 'var(--text-primary)' },
    formGroup: { marginBottom: '20px' },
    formLabel: { display: 'block', marginBottom: '8px', fontWeight: 600, color: 'var(--text-primary)' },
    inlineFlex: { display: 'flex', gap: '12px', alignItems: 'center' },
    opnameInput: { width: '80px', textAlign: 'center' },
    discrepancyPositive: { color: 'var(--success-color)', fontWeight: 'bold' },
    discrepancyNegative: { color: 'var(--danger-color)', fontWeight: 'bold' },
    modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(17, 24, 39, 0.6)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000 },
    modalContent: { backgroundColor: 'var(--bg-content)', padding: '32px', borderRadius: 'var(--radius-lg)', boxShadow: 'var(--shadow-md)', width: '90%', maxWidth: '500px', overflowY: 'auto', maxHeight: '90vh' },
    modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' },
    modalTitle: { margin: 0, fontSize: '1.5rem', fontWeight: 700, color: 'var(--text-primary)' },
    modalCloseButton: { background: 'none', border: 'none', fontSize: '1.75rem', cursor: 'pointer', color: 'var(--text-secondary)' },
    modalFooter: { marginTop: '32px', display: 'flex', justifyContent: 'flex-end', gap: '12px' },
    searchInputWrapper: { position: 'relative', width: '100%', maxWidth: '400px' },
    searchInput: { width: 'calc(100% - 48px)', padding: '10px 16px 10px 40px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-color)', fontSize: '0.95rem' },
    searchInputIcon: { position: 'absolute', top: '50%', left: '12px', transform: 'translateY(-50%)', pointerEvents: 'none' },
};